apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-backend-config
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-backend
data:
  MONGO_URI: "mongodb://{{ .Release.Name }}-database:{{ .Values.databasePort }}/vu-sc-db"