apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - protocol: TCP
    port: {{ .Values.backendPort }}
    targetPort: {{ .Values.backendPort }}
  selector:
    app: {{ .Release.Name }}-backend