apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  JWT_SECRET: |-
    {{ .Files.Get "secrets/jwtSecret.secret" | b64enc }}
