{{ $dbHostPrefix := .Release.Name -}}
{{ $dbPort := .Values.databasePort -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-backend-config
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-backend
data:
  {{ with index .Values.mongodb.auth.databases 0 }}
  MONGODB_URI: "mongodb://{{ $dbHostPrefix }}-database:{{ $dbPort }}/{{ . }}"
  {{ end }}
