apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-backend-config
  labels:
    app: {{ .Release.Name }}-backend
data:
  MONGODB_URI: "mongodb://{{ .Release.Name }}-mongodb:27017/vu-sc-db"