apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-database-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  mongodb-root-user: cm9vdAo= # root
  mongodb-root-password: |-
    {{ .Files.Get "secrets/mongodbRootPass.secret" | b64enc }}
