apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-database-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  mongodb-root-user: cm9vdAo= # root
  mongodb-root-password: |-
    {{ .Files.Get "secrets/mongodbRootPass.secret" | b64enc }}
  {{ with index .Values.mongodb.auth.usernames 0 }}
  mongodb-user: {{ . | b64enc }}
  {{ end }}
  mongodb-passwords: |-
    {{ .Files.Get "secrets/mongodbPass.secret" | b64enc }}
