apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-frontend
      release: {{ .Values.frontendRelease }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-frontend
        release: {{ .Values.frontendRelease }}
    spec:
      containers:
      - name: {{ .Release.Name }}-frontend
        image: {{ .Values.registry }}/vu_sc_frontend:{{ .Values.frontendImageTag }}
        imagePullPolicy: Always # Ensure that updated images are applied
        ports:
        - containerPort: {{ .Values.frontendPort }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.frontendPort }}
