kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-frontend-network-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-frontend
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - ports:
    - port: {{ .Values.frontendPort }}
  egress: []
