apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: manage-secrets-configs-global
subjects:
- kind: User
  name: devops
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: developer
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: secrets-configs-manager
  apiGroup: rbac.authorization.k8s.io