apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resource-reader
rules:
- apiGroups: [""]
  resources: ["deployments", "pods", "services", "endpoints", "jobs", "nodes", "secrets", "configmaps"]
  verbs: ["get", "watch", "list"]