apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-tls-secret
  namespace: {{ .Values.namespace }}
data:
  tls.crt: |-
    {{ .Files.Get "tls/vu-sc.crt" | b64enc }}
  tls.key: |-
    {{ .Files.Get "tls/vu-sc.key" | b64enc }}
type: kubernetes.io/tls