apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gcp-cluster-role
rules:
- apiGroups: [""]
  resources: ["deployments", "pods", "services", "endpoints", "jobs", "nodes", "secrets", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]